services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
      POSTGRES_PORT: 5432
    expose:
      - 5432
